"""Generate the v5 ladder campaign: configs + queue TSV.

Owner directives (2026-07-12): after the 0.6B smoke, fill the queue with a
sequence of models of INCREASING size for the THREE best losses of the
completed 1.7B loss grid, commuting ALL teaching styles — censoring
{remove, pad_random} x rag_scope {chapter, window} — to decide which style
is better. Per-model teacher-recitation ceilings run BEFORE that model's
arms (RAG-authority issue: a teacher that answers without attending to the
retrieval turn disqualifies its arms before they burn GPU).

The training recipe is held fixed across the grid (lossgrid crown recipe:
summed schedule, stride-1 sliding credit, teacher_kl readout, anchor-KL,
frozen teacher copy, bucketed B8); each arm pins exactly {model, loss+slide,
examples_path(scope), compaction}. Budget: 6 epochs x 2071 items = 12,426
matched items per arm.

Usage:
    python scripts/gen_v5_campaign.py          # writes configs + queue
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# ladder rungs: (tag, HF name, train need_mb, cache need_mb, offload_adam)
MODELS = [
    ("0p6b", "Qwen/Qwen3-0.6B", 16000, 12000, False),
    ("1p7b", "Qwen/Qwen3-1.7B", 42000, 18000, False),
    ("4b", "Qwen/Qwen3-4B", 66000, 30000, True),
]

# top-3 losses of the completed loss grid (runs/lossgrid_report.csv,
# final mean recall at matched budget), each with its winning slide.
# jacobian_lens_kl needs a per-model lens artifact: present for 0.6B/1.7B;
# Qwen3-4B has none yet -> that combo is deliberately NOT queued (build the
# lens in ../jacobian-lens first, then extend the queue).
JLENS = {
    "0p6b": "../jacobian-lens/out/lenses/Qwen3-0.6B_jacobian_lens_n1000.pt",
    "1p7b": "../jacobian-lens/out/lenses/Qwen3-1.7B_jacobian_lens_n466.pt",
}
LOSSES = [
    # (tag, hidden_loss, conn_window/readout blocks, extra train keys)
    ("jlenskl1", "jacobian_lens_kl", 1, "jlens"),
    ("huber2", "huber", 2, None),
    ("lenskl1", "lens_kl", 1, None),
]
SCOPES = ("window", "chapter")
CENSORS = ("remove", "pad_random")

BASE_TPL = """\
# v5 ladder base — {name}. Recipe fixed across the style grid; arms pin
# {{loss+slide, examples_path(scope), compaction}} only. Generated by
# scripts/gen_v5_campaign.py — regenerate, don't hand-edit.
run_name: {prefix}_{tag}_base_never_trained
model:
  name: {name}
data:
  examples_path: data/combined/examples_{prefix}_window.jsonl
mask:
  mode: {mode}
  compaction: remove
train:
  method: layerwise
  run_class: method
  schedule: summed
  epochs: 6
  lr: 1.0e-5
  micro_batch: 8
  grad_accum: 8
  batching: bucketed
  hidden_loss: huber
  conn_window: 1
  conn_stride: 1
  readout_window_blocks: 1
  readout_weight: 0.5
  window_hidden_weight: 1.0
  readout_source: teacher_kl
  anchor_kl_weight: 0.5
  anchor_path: data/anchors_es_v2.txt
  frozen_teacher_copy: true{offload}
  lora:
    enabled: false
eval:
  every_epochs: 1
  recall_corpora: [machado, quijote_ch1, quijote_ch4]
  standard_damage_every_epochs: 1
  standard_damage_limit: 16
  standard_damage_batch_size: 8
  generation_batch: 8
"""

ARM_TPL = """\
# v5 arm: {loss} (slide {slide}) x {scope}-RAG x {censor}. Generated by
# scripts/gen_v5_campaign.py.
run_name: {run}
data:
  examples_path: data/combined/examples_{prefix}_{scope}.jsonl
mask:
  compaction: {censor}
train:
  hidden_loss: {loss}
  conn_window: {slide}
  readout_window_blocks: {slide}{jlens}
"""

CACHE_TPL = """\
# v5 teacher cache identity: {tag} x {scope} x {censor} (generation +
# premise + recitation telemetry live in the hashed cache dir). Generated
# by scripts/gen_v5_campaign.py.
run_name: {prefix}cache_{tag}_{scope}_{censor}
model:
  name: {name}
data:
  examples_path: data/combined/examples_{prefix}_{scope}.jsonl
mask:
  mode: {mode}
  compaction: {censor}
"""


def main(prefix: str = "v5", mode: str = "rag_tool",
        gen_extra_tokens: int = 32, budget_multiplier: float = 1.0) -> None:
    cfg_dir = ROOT / "configs" / "experiments" / prefix
    queue = ROOT / "scripts" / f"queue_{prefix}_ladder_20260712.tsv"
    cfg_dir.mkdir(parents=True, exist_ok=True)
    rows: list[str] = []

    def row(done: str, mb: int, after: str, cmd: str, gpus: int = 1) -> None:
        rows.append(f"{done}\t{mb}\t{after}\t{cmd}\t{gpus}")

    py = ".venv/bin/python"
    for tag, name, train_mb, cache_mb, offload in MODELS:
        base = f"configs/experiments/{prefix}/base_{tag}.yaml"
        (ROOT / base).write_text(BASE_TPL.format(
            tag=tag, name=name, prefix=prefix, mode=mode,
            offload="\n  offload_adam: true" if offload else ""),
            encoding="utf-8")
        rows.append(f"# ---- {name} rung "
                    f"(ceilings/floors first: RAG-authority gate) ----")
        # budget_multiplier=1.0 is teacher_ceiling.py's own default, so
        # omitting the flag entirely keeps the unqualified (v5) invocation
        # byte-identical to before this knob existed.
        mult_flag = (f"--budget-multiplier {budget_multiplier} "
                    if budget_multiplier != 1.0 else "")
        # evaluate.py writes a directory containing tasks.json, not a JSON
        # file at --out itself.  The old .json marker never appeared and
        # made the scheduler rerun this base evaluation indefinitely.
        # Built FIRST and threaded through every ceiling's "after": the gate
        # reads ceiling + floor_pad + floor_plain, but the scheduler only
        # tracks one dependency edge per row, and floor_plain previously had
        # "after: -" with no ordering relative to the gate that consumes it
        # — a race the gate crashed on (FileNotFoundError) whenever its
        # floor_pad edge resolved before floor_plain happened to finish
        # (2026-07-12).
        floor_plain = f"runs/{prefix}_refs/{tag}_floor_none/tasks.json"
        row(floor_plain, cache_mb, "-",
            f"{py} scripts/teacher_ceiling.py --experiment "
            f"configs/experiments/{prefix}/cache_{tag}_window_remove.yaml "
            f"--context-scope none "
            f"--generation-batch 8 "
            f"--max-extra-tokens {gen_extra_tokens} {mult_flag}"
            f"--recall-corpora machado quijote_ch1 quijote_ch4 "
            f"--out {floor_plain}")
        # ceiling per scope, then its padded floor — both chained after
        # floor_plain so the gate's single dependency edge (on floor_pad)
        # transitively guarantees all three of its inputs exist.
        ceilings, floors = {}, {}
        for scope in SCOPES:
            cache_cfg = f"configs/experiments/{prefix}/cache_{tag}_{scope}_remove.yaml"
            ceil = f"runs/{prefix}_refs/{tag}_ceiling_{scope}.json"
            row(ceil, cache_mb, floor_plain,
                f"{py} scripts/teacher_ceiling.py --experiment {cache_cfg} "
                f"--context-scope {scope} --generation-batch 8 "
                f"--max-extra-tokens {gen_extra_tokens} {mult_flag}"
                f"--recall-corpora machado quijote_ch1 quijote_ch4 --out {ceil}")
            ceilings[scope] = ceil
        for scope in SCOPES:
            floor_pad = f"runs/{prefix}_refs/{tag}_floor_padrandom_{scope}.json"
            row(floor_pad, cache_mb, ceilings[scope],
                f"{py} scripts/teacher_ceiling.py --experiment "
                f"configs/experiments/{prefix}/cache_{tag}_{scope}_pad_random.yaml "
                f"--context-scope {scope} --context-pad-random "
                f"--generation-batch 8 "
                f"--max-extra-tokens {gen_extra_tokens} {mult_flag}"
                f"--recall-corpora machado quijote_ch1 quijote_ch4 "
                f"--out {floor_pad}")
            floors[scope] = floor_pad
        gates = {}
        for scope in SCOPES:
            gate = f"runs/{prefix}_refs/{tag}_gate_{scope}.json"
            row(gate, cache_mb, floors[scope],
                f"{py} scripts/rag_generation_gate.py --ceiling {ceilings[scope]} "
                f"--floor {floors[scope]} --no-rag {floor_plain} --out {gate}")
            gates[scope] = gate
        # caches: one per scope x censor (generation inside)
        cache_markers = {}
        for scope in SCOPES:
            for censor in CENSORS:
                cache_cfg = f"configs/experiments/{prefix}/cache_{tag}_{scope}_{censor}.yaml"
                (ROOT / cache_cfg).write_text(CACHE_TPL.format(
                    tag=tag, name=name, scope=scope, censor=censor,
                    prefix=prefix, mode=mode),
                    encoding="utf-8")
                marker = f"runs/.{prefix}cache_{tag}_{scope}_{censor}.done"
                cache_markers[(scope, censor)] = marker
                row(marker, cache_mb, gates[scope],
                    f"bash -c '{py} scripts/build_teacher_cache.py "
                    f"--experiment {cache_cfg} && touch {marker}'")
        # arms
        for ltag, loss, slide, extra in LOSSES:
            if extra == "jlens" and tag not in JLENS:
                continue  # no 4B jacobian lens yet — see module docstring
            jlens = (f"\n  jacobian_lens_path: {JLENS[tag]}"
                     if extra == "jlens" else "")
            for scope in SCOPES:
                for censor in CENSORS:
                    run = f"{prefix}_{tag}_{ltag}_{scope}_{censor}"
                    arm = f"configs/experiments/{prefix}/{run}.yaml"
                    (ROOT / arm).write_text(ARM_TPL.format(
                        run=run, loss=loss, slide=slide, scope=scope,
                        censor=censor, jlens=jlens, prefix=prefix),
                        encoding="utf-8")
                    ck = f"runs/{run}/checkpoint"
                    row(ck, train_mb, cache_markers[(scope, censor)],
                        f"{py} scripts/train.py --config {base} "
                        f"--experiment {arm}")
                    row(f"runs/{run}/eval/tasks.json", cache_mb, ck,
                        f"{py} scripts/evaluate.py --config {base} "
                        f"--experiment {arm} --checkpoint {ck} "
                        f"--out runs/{run}/eval "
                        f"--generation-batch 8 "
                        f"--recall-corpora machado quijote_ch1 quijote_ch4")
                    row(f"runs/standard_damage/{run}.json", cache_mb, ck,
                        f"{py} scripts/standard_destruction_eval.py "
                        f"--config {base} --experiment {arm} "
                        f"--checkpoint {ck} "
                        f"--out runs/standard_damage/{run}.json "
                        f"--tasks arc_easy arc_challenge hellaswag "
                        f"--limit 100 --batch-size 16 --stage-to-local")

    header = (
        f"# {prefix} ladder campaign (2026-07-12, mask.mode={mode}): "
        "3 best lossgrid losses x "
        "{remove,pad_random} x {window,chapter}, models in increasing size.\n"
        "# done_file\tneed_mb\tafter\tcommand\tn_gpus\n"
        "# NOTE 4B x jacobian_lens_kl is NOT queued: no Qwen3-4B lens in\n"
        "# ../jacobian-lens/out/lenses yet — build it there first, then\n"
        "# regenerate with scripts/gen_v5_campaign.py.\n"
        "# Each scope then needs a passing generation gate before caches/arms:\n"
        "# generation must stop naturally and real RAG must beat its matched\n"
        "# random-context floor on every corpus.\n")
    queue.write_text(header + "\n".join(rows) + "\n", encoding="utf-8")
    n_arms = sum(1 for r in rows
                 if r.split("\t")[0].endswith("/checkpoint"))
    print(f"wrote {queue.name}: {len(rows)} rows, {n_arms} arms, "
          f"configs under {cfg_dir.relative_to(ROOT)}")


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--prefix", default="v5",
                    help="campaign prefix: config dir, run names, dataset id, "
                         "refs dir, queue file (default v5)")
    ap.add_argument("--mode", default="rag_tool",
                    choices=["rag_tool", "rag_system"],
                    help="mask.mode for every generated config")
    ap.add_argument("--gen-extra-tokens", type=int, default=32,
                    help="teacher_ceiling.py --max-extra-tokens (FIXED "
                         "margin) for every ceiling/floor call (default 32 "
                         "matches the script's own default)")
    ap.add_argument("--budget-multiplier", type=float, default=1.0,
                    help="teacher_ceiling.py --budget-multiplier (scales "
                         "with reference length) for every ceiling/floor "
                         "call; default 1.0 matches the script's own "
                         "default. Chapter-scope Quijote references run to "
                         "hundreds of tokens, so a >1 multiplier — not a "
                         "bigger flat --gen-extra-tokens — is the fix for "
                         "framing-driven hard cuts diagnosed by "
                         "rag_generation_gate.py; never relax the gate "
                         "itself")
    a = ap.parse_args()
    main(prefix=a.prefix, mode=a.mode, gen_extra_tokens=a.gen_extra_tokens,
        budget_multiplier=a.budget_multiplier)
    sys.exit(0)
